### PR TITLE
RL/RH bit test fix

### PR DESCRIPTION
**Pull request by jmarcgit**
Hi,

I just found a small bug in the RH/RL processing when moving byrte value to 16 bits registers

### CODE REVIEW

**Comment by hn** [comment]
Well, I'm really excited that anyone is using this stuff I wrote over 20 years ago ;-) I would be interested to know what you are currently using this for.

I'm merging this unchecked and untested because I currently have no insight into the details anymore.

**Comment by jmarcgit** [comment]
Hi,

I'm using this to reverse engoneer some old car ecus. Works very well.

Basically the error is related to moving a byte value to a 16 bit register.
You test the tailing bit to check if the move is for low or high part of
the register. But the length of the token is 4 bits only not 8.

Thinking about adding a symbol table as an optional input...

Anyway great piece of code 👍

Le mar. 16 août 2022 à 09:36, Hajo Noerenberg ***@***.***> a
écrit :

**Comment by jmarcgit** [comment]
hi again,

I find it confusing that the addresses are formatted in 32 bit format.
Makes believe that the operation is waiting for a 32 bit addresses..
Do you think there is any reason for that ?.

J

**Comment by hn** [comment]
Hi, I don't remember, very likely there is no particular reason for it. I wrote the whole thing more or less in one afternoon and it surprisingly worked for my use case :)

Feel free to send me more patches, I will merge them later.

**Comment by Azq2** [comment]
> Well, I'm really excited that anyone is using this stuff I wrote over 20 years ago ;-) I would be interested to know what you are currently using this for.
> 
> I'm merging this unchecked and untested because I currently have no insight into the details anymore.

20 years ago, you were reverse engineering Siemens phones  (EGOLD)?

**Comment by hn** [comment]
>20 years ago, you were reverse engineering Siemens phones (EGOLD)?

The Sagem 939 phone is also based on the C166 processor. And for its firmware settings checksum it uses a proprietary keyed sponge-style MAC combining a 256-byte permutation S-box with a byte-wide LFSR (feedback polynomial 0x163).

**Comment by Azq2** [comment]
> > 20 years ago, you were reverse engineering Siemens phones (EGOLD)?
> 
> The Sagem 939 phone is also based on the C166 processor. And for its firmware settings checksum it uses a proprietary keyed sponge-style MAC combining a 256-byte permutation S-box with a byte-wide LFSR (feedback polynomial 0x163).

Your script is still useful. I actively use it for reverse engineering Siemens phones on the EGOLD platform. Thank you!

**Pull request merged**
